# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# version: 2.1
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:7.10
      
#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#           - demo-{{ checksum "package.json" }}

#       - run: chmod +x ./setup_libxcb.sh
#       - run: sh ./setup_libxcb.sh
#       - run: npm install

#       - save_cache:
#           paths:
#             - node_modules
#           key: demo-{{ checksum "package.json" }}
        
#       # run tests!
#       - run: npm test


version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - demo-{{ checksum "package.json" }}
      - run: chmod +x ./setup_libxcb.sh
      - run: sh ./setup_libxcb.sh
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: demo-{{ checksum "package.json" }}

      - run: npm test
# workflows:
#     build-and-test:
#       jobs:
#         - build-and-test