version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - demo-{{ checksum "package.json" }}
      - run: chmod +x ./setup_libxcb.sh
      - run: sh ./setup_libxcb.sh
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: demo-{{ checksum "package.json" }}

      - build-only:
        - run: npm run build
      - test-only: 
        - run: npm run test
        requires:
          - build-only
workflows:
    build-and-test:
      jobs:
        - build-and-test