version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - demo-{{ checksum "package.json" }}
      - run: chmod +x ./setup_libxcb.sh
      - run: sh ./setup_libxcb.sh
      - run: npm install
      - run:
          name: install pm2
          command: 'sudo npm install -g pm2'
      - save_cache:
          paths:
            - node_modules
          key: demo-{{ checksum "package.json" }}

      - run: npm run build

      - run: npm run test
      - run:
          name: storing local IP address
          command: node -p "require('ip').address()" > ip.txt
      - run:
          name: waiting for node server to start
          command: 'wget --retry-connrefused --waitretry=5 -t 5 "http://$(cat ip.txt):3009" > /dev/null'

      - run: npm run begin-test
workflows:
    build-and-test:
      jobs:
        - build-and-test
            filters: # using regex filters requires the entire branch to match
                branches:
                  only: # only branches matching the below regex filters will run
                    - master
                    - circleci-project-setup
                    # - /feature\/.*/