# workflows:
#   version: 2
#   build-test-and-deploy:
#     jobs:
#       - build
#       - test1:
#           requires:
#             - build
#       - test2:
#           requires:
#             - test1
#       - deploy:
#           requires:
#             - test2
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - demo-{{ checksum "package.json" }}
      - run: chmod +x ./setup_libxcb.sh
      - run: sh ./setup_libxcb.sh
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: demo-{{ checksum "package.json" }}

      - run: npm run build
      - test-only: 
        - npm run test
        requires:
          - build-and-test
workflows:
    build-and-test:
      jobs:
        - build-and-test