version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - demo-{{ checksum "package.json" }}
      - run: chmod +x ./setup_libxcb.sh
      - run: sh ./setup_libxcb.sh
      - run: npm install
      - run:
          name: install pm2
          command: 'npm install pm2 -g'
      - save_cache:
          paths:
            - node_modules
          key: demo-{{ checksum "package.json" }}

      - run: npm run start
      # - run: npm run test
workflows:
    build-and-test:
      jobs:
        - build-and-test